### ISSUE TITLE
GT of the shanghaitech

### ISSUE THREAD

**Issue by zw-absin** [ristea/aed-mae#3]
Hello, I'd like to know how to get the .txt files like '/media/alin/hdd/Transformer_Labels/Shanghai_gt/01_0025.txt'. Are these files pixel_mask or frame_mask? How to transform .npy file to .txt file? Thank you!

**Comment by CroitoruAlin** [comment]
Hello! We added a zip archive containing these files in the drive folder, where the checkpoints are stored

**Comment by houchenfeng** [comment]
> Hello! We added a zip archive containing these files in the drive folder, where the checkpoints are stored

but it`s seem to be empty. ?

**Comment by CroitoruAlin** [comment]
Hello! Someone deleted the files, we uploaded them again.

**Comment by houchenfeng** [comment]
> Hello! Someone deleted the files, we uploaded them again.

Thank you for your response. I am now able to download the file successfully.
