### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 1s3ss** [ristea/aed-mae#4]
Hi! Can I know the format of the folder or file under the dataset, something like this：
“
--Avenue Dataset
----train
------frames
----test
....
--SanhaiTech
----train
------frames
....
"

**Comment by CroitoruAlin** [comment]
Hello,

The folder structure is something like this:
- Avenue Dataset
-- train
--- frames
--- frames_abnormal
--- masks
--- masks_abnormal
--- gradients
--test
--- frames
--- gradients

**Comment by hcf783** [comment]
> Hello,
> 
> The folder structure is something like this:
> 
> * Avenue Dataset
>   -- train
>   --- frames
>   --- frames_abnormal
>   --- masks
>   --- masks_abnormal
>   --- gradients
>   --test
>   --- frames
>   --- gradients

How do I get masks for train? Is it made from avene.mat?

**Comment by JPerAsperaadAstra** [comment]
Hi, dear author @CroitoruAlin , do we need to split abnormal frames and masks into individual folders?(frames_abnormal, masks_abnormal)

**Comment by CroitoruAlin** [comment]
Hello, yes

**Comment by JPerAsperaadAstra** [comment]
Thx, but how do we get frames_abnormal and masks_abnormal? There seems to be no description about this step in the README. Could you please give us an instruction about how to generate these two folders' content?

**Comment by CroitoruAlin** [comment]
There is one, please see step 2 from preprocessing. So, you have to run main.py from create_anomalies located in utils.

**Comment by JPerAsperaadAstra** [comment]
Thx for your patient reply. Yes, I followed the instructions for processing UBnormal dataset to generate abnormal sequences and integrate them into Avenue dataset with <create_abnormal_sequences.py> and <integrate_abnormal_objects.py>, and I got a folder named "Avenue_aug_abnormal_masks" according to the default argument in util/create_anomalies/arguments.py
Avenue_aug_abnormal_masks contains 2 sub-folders: frames and masks. Are these 2 sub-folders related to frames_abnormal and masks_abnormal? If so, what does the "masks" folder mean under Avenue/train/masks? (I guess it refers to Avenue dataset's gt masks?)
Little bit confused, looking forward to your reply :)

**Comment by inaomIIsfarell** [comment]
Hi! I download **Avenue Dataset** from official  website https://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html
but the folder structure is : 
Avenue Dataset
├── testing_videos
├── testing_vol
├── training_videos
└── training_vol

I'd like to know how to download the Datasets correctly.

**Comment by CroitoruAlin** [comment]
As I mentioned in a previous comment, this is the structure:
Avenue Dataset
-- train
--- frames
--- frames_abnormal
--- masks
--- masks_abnormal
--- gradients
--test
--- frames
--- gradients

You have to extract the frames from the video and put them in directories, like this:
-- train
--- frames
----video1
----video2
...
After this you should be able to run the preprocessing steps.

**Comment by shreethar** [comment]
> As I mentioned in a previous comment, this is the structure: Avenue Dataset -- train --- frames --- frames_abnormal --- masks --- masks_abnormal --- gradients --test --- frames --- gradients
> 
> You have to extract the frames from the video and put them in directories, like this: -- train --- frames ----video1 ----video2 ... After this you should be able to run the preprocessing steps.



Hi @CroitoruAlin ,
I've done the preprocessing,. but under my avenue folder, I don't have mask and I'm not sure how to get it
-Avenue
--train
---frames (extracted from avenue vide)
---frames_abnormal (gotten after integrating abnormal UBNormal data into Avenue)
---masks_abnormal (gotten after integrating abnormal UBNormal data into Avenue)
---gradients (gotten via calculating the difference between consecutive frames)


I am not sure how to get the ```masks``` folder

**Comment by YuFu7** [comment]
> masks_abnormal



> > 正如我在之前的评论中提到的，结构是这样的：Avenue Dataset -- 训练---帧--- frames_abnormal ---掩码--- masks_abnormal ---梯度 --测试---帧---梯度
> > 您必须从视频中提取帧并将它们放入目录中，如下所示： -- 训练---帧 ----video1 ----video2 ...在此之后，您应该能够运行预处理步骤。
> 
> 嗨，我已经完成了预处理。但是在我的 avenue 文件夹下，我没有掩码，我不确定如何获得它 -Avenue --train ---frames（从 avenue vide 中提取）---frames_abnormal（将异常 UBNormal 数据集成到 Avenue 后获得）---masks_abnormal（将异常 UBNormal 数据集成到 Avenue 后获得）---梯度（通过计算连续帧之间的差异获得）
> 
> 我不确定如何获取文件夹`masks`

Hello, I think the masks folder is obtained through line 13 of 'til/create_nameses/integrate_abnormal_obs.spy'. May I ask how 'frames_abnormal' and 'masks_abnormal' are obtained?
