### ISSUE TITLE
Cannot test on datasets other than avenue

### ISSUE THREAD

**Issue by JPerAsperaadAstra** [ristea/aed-mae#9]
Hello, dear authors, a problem encountered when replicating the experiment on dataset ShanghaiTech
in engine_train.py line95~101:

```
for vid in np.unique(videos):
        pred = predictions[np.array(videos) == vid]
        pred = np.nan_to_num(pred, nan=0.)
        if args.dataset=='avenue':
            pred = filt(pred, range=38, mu=11)
        else:
            raise ValueError('Unknown parameters for predictions postprocessing')
```

how should we filter datasets other than avenue if we want to get the test result?

**Comment by Rusiee** [comment]
你好，我打不开这个链接https://drive.google.com/drive/folders/1Qpx1ZohOPgdeR0uMZkLqFaaNCOpcZ_aF ](https://drive.google.com/drive/folders/1Qpx1ZohOPgdeR0uMZkLqFaaNCOpcZ_aF 请问您处理这个任务的时候是怎么做的
